# Generated by Django 3.2.9 on 2021-11-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='fileupload',
            field=models.FileField(default=1, upload_to='files'),
            preserve_default=False,
        ),
    ]
